### ISSUE TITLE
Lazy initialization / Proxy

### ISSUE THREAD

**Issue by Leomuck** [Level-2/Dice#104] opened 2016-02-16 13:49 UTC
I'm having a class where only a few parts of it use a quite big object that gets injected through the constructor. Now whenever those aren't actually used the initialization of this object is useless and reduces performance. Is there any way to have something as lazy initialization or proxy objects? Or is this only an issue because my class is structured poorly?

Another useful case for this would be caching. Say I am only using a model if there is no cache for a file. Now my MVC structure doesn't really care for that, so the model gets instantiated anyway. But since I am not using any of it, it would be nice if the stuff that gets injected into the model layer doesn't take too much loading time.

**Comment by TomBZombie** [comment] 2016-02-27 16:40
Can you provide a basic outline of the class structure? Just the skeleton code with the classes and their constructors so I can see how they work?

Generally if you find yourself "not using an object" after requesting it in a constructor, you might want to refactor the code (this isn't always possible). However, proxy objects can actually add an overhead.

Keep in mind that constructors shouldn't be doing anything complex and should run very quickly. Generally speaking, the different between creating a proxy object and creating a real object should be near zero... and if you factor in the cases where the object is used and created by the proxy, the proxy is actually an overhead because both a proxy and the real object are created and the extra functions called.

If there are cases where the constructor is actually doing something heavy, refactor the class so it's not. This is essentially an encapsulation issue: "I know that constructing this class is slow, therefore I'll program around it". If the problem is that "constructing the class is slow" then fix that and speed up the constructor instead of introducing workarounds and extra code. 

Here's an example of how to do it with PDO http://stackoverflow.com/questions/5484790/auto-connecting-to-pdo-only-if-needed which imho should really be its default behaviour.

**Comment by MrBenGriffin** [comment] 2016-07-15 11:45
We've been working on a similar sort of issue.  
There is a use case where dice's dependency on __construct() means that we are less able to use fluid inheritance, because our extended classes must now need to 'know' about their parent classes dependencies...

e.g. 
````php
abstract class AbstractBar {
  private $foo;
  public function __construct(Foo $foo) { $this->foo = $foo; } 
  protected function fooThing() { return $this->foo->thing(); }
}

class MyBar extends AbstractBar {
  public function  __construct(Bim $bim) { $this->bim = $bim; } 
//Argh!!! Need to use parent::__construct( but I have no dependency on Foo here) !!! 
  public function run() { return [$this->fooThing(),$this->bim->thing()];}
}
````

So, the above is (obviously) an example only, but we have real use-cases for this where refactoring introduces additional problems for us.

We have come to several solutions for dealing with this.  
One method is a sort of lazy-evaluation methodology which depends upon a dependency-holding controller class keeping an array of dependencies. 
This allows extended classes to NOT having a __construct method at all(!), but to rely upon the controller to evaluate them against their own dependencies.  
We can always extend the controller class if we need to have a specialised dependency.

````php
class Controller { //keeps dependencies of extended classes.
   protected $deps = [];
   public function __construct(Bar $bar) {
        $this->deps[Bar::class]=$bar;
    }
    protected function resolve($closure) {
        $closure_parameters=[];
        $reflection = new ReflectionFunction($closure);
        foreach ($reflection->getParameters() as $parameter) {
            $closure_parameters[] = @$this->deps[$parameter->getClass()->name];
        }
        $reflection->invokeArgs($closure_parameters);
    }
    public function run() {
        return $this->resolve($this->deps[Bar::class]->run());
    }
}
//class AbstractBar is as above.
class Bar extends AbstractBar { //no constructor means the abstract construct gets called.
  public function run() { 
   return function (Bim $bim) { return [$this->fooThing(),$bim->thing()]; } ;
 }
}
````

**Comment by MrBenGriffin** [comment] 2016-07-15 12:27
@TomBZombie,  Looking at what I wrote above makes me think that hijacking the __construct() isn't exactly 'right', for inversion of control / dependency injection unless there is a means of invoking parent constructors without having to be explicit about them. 

I'm not saying Dice is wrong - we are committed to it - but I wonder if maybe there is a deeper issue which could be addressed by using some sort of method such as _depends() which does the dependency legwork without interfering with inheritence?

Just a thought.

**Comment by TomBZombie** [comment] 2016-07-15 13:37
Can you explain this better, this code:

```php
class MyBar extends AbstractBar {
  public function  __construct(Bim $bim) { $this->bim = $bim; } 
//Argh!!! Need to use parent::__construct( but I have no dependency on Foo here) !!! 
  public function run() { return [$this->fooThing(),$this->bim->thing()];}
}
````

Has problems regardless of Dice. Either way you need to call parent::__construct(), whether Dice does it somehow or manually you need a reference to `$foo` This is a design constraint imposed by OOP and not by Dice. There's no way Dice can handle situations that cannot be handled normally.

**Comment by TomBZombie** [comment] 2016-07-15 13:41
(the real solution of course is that Inheritance should be avoided and use composition instead. Inheritance introduces tight coupling and generally speaking should be avoided)

**Comment by solleer** [comment] 2016-07-15 13:48
What is composition?

**Comment by MrBenGriffin** [comment] 2016-07-15 13:49
Hi thanks for the response as ever!

There are ways of avoiding sticking dependencies into the   __construct(), 
for instance by using setters.  (I'm not saying that it's a good thing!)

My point is about the entire idea of DI and encapsulation while using inheritence.  

I believe that there is a good reason to use inheritence, especially when you are looking specifically at the strong relationship of "is-a-type-of", as it reduces code complexity, assists in refactoring, enables specialisation, and a whole bunch of other very OO things.

So we may have a base class that itself has a set of dependencies (eg a PDO or something) and that does all the grindwork, we may want to have a lightweight specialised extension that only wants to know about it's specialised case.

One method we thought of was to avoid using constructors at all on the extended class (see the controller concept above). But this got me thinking of if there is -any way at all- of obscuring the base class dependencies from the extended class.

So, the following is a (messy) attempt at it. 
_The sole purpose here is to keep Foo from having to know about it's abstract class's dependencies, and nothing else_.

````php
class AbstractFoo {
   protected $_deps = [Bar::class=>null,Bim::class=>null];
   private function __construct($deps=[]) {
   		$this->_deps = array_merge($this->_deps,array_intersect_key($_deps,$this->_deps));
   } 
}

class Foo { //doesn't know about the AbstractClasses dependencies
   protected $_deps = [Baz::class=>null];
   private function __construct($deps=[]) {
   	$this->_deps = array_merge($this->_deps,array_intersect_key($_deps,$this->_deps));
   	parent::__construct($this->_deps);
   } 
}

$bar = new Bar(); $bim = new Bim(); $baz = new Baz();
$foo = new Foo([Bar::class=>$bar,Bim::class=>$bim,Baz::class=>$baz]);

````

**Comment by TomBZombie** [comment] 2016-07-15 13:53
> The sole purpose here is to keep Foo from having to know about it's abstract class's dependencies, and nothing else.

**Comment by TomBZombie** [comment] 2016-07-15 14:02
> The sole purpose here is to keep Foo from having to know about it's abstract class's dependencies, and nothing else.

But when you're saying Foo *is-a* Bar then it makes sense for `Foo` to have `Bar`'s dependencies.

As I said before, if this is your goal, then inheritance is not the answer:

```php
class Foo  { //doesn't know about the AbstractClasses dependencies
   
   public function __construct(AbstractClasss $class) {
   	//I don't know what dependencies $class has due to encapsulation
   	
    $class->whatever();
   } 
}
```

Refactor to use composition instead of inheritance and your goal is achieved :)

There is no is-a relationship that can't be better expressed as has-a. For example, "An employee is a person"? Refactor to "A person that has a job" "A cat is an animal", refactor to "A cat has fur and 4 legs"

**Comment by MrBenGriffin** [comment] 2016-07-15 14:02
@solleer, there's a good article on why one should prefer composition over inheritence here https://en.wikipedia.org/wiki/Composition_over_inheritance

**Comment by solleer** [comment] 2016-07-15 14:03
Thanks

**Comment by MrBenGriffin** [comment] 2016-07-15 14:05
@TomBZombie, I know all about why one should prefer composition - and I agree - but I think there are really good use-cases for inheritence, and I disagree that specialised extensions should have to know anything whatsoever about their base classes. I am sure I can think of plenty of examples.

**Comment by TomBZombie** [comment] 2016-07-15 14:13
>  I disagree that specialised extensions should have to know anything whatsoever about their base classes. I am sure I can think of plenty of examples.

Unfortunately you're disagreeing with the design of OOP. Inheritance breaks encapsulation, either live with it or don't use inheritance. This isn't a problem that a DI container can solve (without itself breaking encapsulation or coupling the container to the class, which is not a good idea).


Consider this:

```php

class Animal {
	private $numLegs;

	public function __construct($numLegs) {
		$this->numLegs = $numLegs;
	}
}


class Cat extends Animal {
	private $furColour;	

	public function __construct($furColour) {
		parent::__construct(4);
		$this->furColour = $furColour;
	}

}

class Reptile extends Animal {
	private $scaleColour;	

	public function __construct($numLegs, $scaleColour, $scalePattern) {
		parent::__construct($numLegs);
		$this->scaleColour = $scaleColour;
		$this->scalePattern = $scalePattern;
	}
}

Ok we can instantiate these like this:

```php

$snake = new Reptile(0, 'brown', 'triangular');
$cat = new Cat('black');

```

It's easy to refactor this into a more OO  solution and add flexiblity in the process:


```php

class Animal  {
	public function __construct($numLegs, Texture $texture) {

	}
}

interface Texture {
	//...
}

```

And then we have the flexibility of being able to have any texture on any animal:


```php

$cat = new Animal(4, new Fur('black'));
$snale = new Animal(0, new Scale('brown', 'triangular'));

```

**Comment by MrBenGriffin** [comment] 2016-07-15 14:16
@TomBZombie, of course your animal example is great for showing when composition should be preferred over inheritance. 
However, I disagree when you imply that inheritence has no place in OOP.  
There are alternatives to the above, which we have considered, including using traits - but (IMO) traits have their own problems.

**Comment by TomBZombie** [comment] 2016-07-15 14:28
You can also use static properties:

```php
class AbstractFoo {
   public static $foo;


   public function talkToFoo()  {
   	self::foo->whatever();
   }


}


class Bar extends Foo {
	//now doesn't need a foo instance
	public function __construct() {
		$this->talkToFoo();
	}
}


AbstractFoo::Foo = new Foo();


$bar = new Bar();

```

Of course this introduces a completely new set of problems.

**Comment by MrBenGriffin** [comment] 2016-07-15 14:28
haha, yes - we don't want to use statics. That was my very first suggestion, and it was shot down in the flames that it deserved :-D

**Comment by TomBZombie** [comment] 2016-07-15 14:36
Here's a real hacky workaround:

````php

class AbstractFoo {
	private $bar;
}


class MyFoo extends AbstractFoo {
	
	private $bim;

	//I don't need to know about bar
	public function __construct($bim) {
		$this->bim = $bim;
	}

}


//create the $bar instance:

$bar = new Bar();

$createMyFoo = function($bim) use ($bar) {
	
	$foo = new MyFoo($bim);

	//Hack to write to private properties
	$write = function($bar) {
		$this->bar = $bar;
	};

	$write = $write->bindTo($foo, $foo);

	$write($bar);

	return $foo;

};


```

Now use `$foo = $createMyFoo($bim);` in place of `new MyFoo($bim)` throughout the application.

**Comment by MrBenGriffin** [comment] 2016-07-15 14:47
Haha - that's funny! And it's a nice introduction to bindTo() ...

**Comment by TomBZombie** [comment] 2016-07-15 14:59
Am I right in thinking this is an XY problem. "If I can do this it will solve another problem?" I suspect what you're having a problem with is that when you have:


```
class Bar extends AbstractFoo {
 public function __construct($foo, $bim) {
parent::__construct($foo);
$this->bim = $bim;
}
}
```

And the problem with this is that you have $n classes  with `extends AbstractFoo` and if `AbstractFoo::__construct)` changes , you have to change all the child classes. Is that correct?

**Comment by MrBenGriffin** [comment] 2016-07-15 15:03
Yep

**Comment by TomBZombie** [comment] 2016-07-15 15:07
You could try this:

```php
class Bar extends AbstractFoo {
	public function (Bim $bim, ...$foosDeps) {
		parent::__construct(...$foosDeps)
	}
}
```

You'd still need to supply the correct dependencies to each `new` call but it would save some work:

```php

$bar = new Bar($bim, $fooDep1, $fooDep2, $fooDep3);

```

With dice you could just use:

```php
$dice->addRule('abstractfoo', ['constructParams' => [new FooDep1, new Foodep2]);

$bar = $dice->create('bar');
```

This would work as long as all of `Bar`'s other constructor arguments were type hinted and weren't the same type (Or subtype) as any of `AbstractFoo`'s dependencies.

**Comment by solleer** [comment] 2016-07-15 15:12
I have this class
```php
namespace MVC\Model\Form;
class Save implements \MVC\Model\Form {
    protected $maphper;
    protected $validator;
    public $successful = false;
    public $submited = false;
    public $data;

    public function __construct(\Maphper\Maphper $maphper, \Respect\Validation\Rules\AllOf $validator = null) {
        $this->maphper = $maphper;
        $this->validator = $validator;
    }

    public function main($data = null) {
        $this->submitted = false;
        $this->data = $this->maphper[$data[0]];
        return true;
    }

    public function submit($data) {
        $this->submitted = true;
        $this->data = (object) $data;
        if (!$this->validator->validate((array) $this->data)) return false;
        $this->maphper[] = $this->data;
        return true;
    }

    public function success() {
        $this->successful = true;
    }
}
```
and this class extends it
```php
namespace MVC\Model\Form;
class SaveFile extends Save {
    protected $uploader;

    public function __construct(\Maphper\Maphper $maphper,
            \Respect\Validation\Rules\AllOf $validator, \Upload\File $uploader = null) {
        $this->uploader = $uploader;
        parent::__construct($maphper, $validator);
    }

    protected function setNewFileName() {
        $newFileName = time() . '-' . $this->uploader->getName();
        $this->uploader->setName($newFileName);
    }

    public function submit($data) {
        $this->submitted = true;
        $this->setNewFileName();
        // Upload File
        try {
            $this->uploader->upload();
        } catch (\Exception $e) {
            $errors = $this->uploader->getErrors();
            return false;
        }
        $data['file_name'] = $this->uploader->getNameWithExtension();
        return parent::submit($data);
    }
}
```
Would it be better to use composition. It just seems that extending makes things easier by not having to redefine the main and success functions.

**Comment by TomBZombie** [comment] 2016-07-15 15:23
In this case there's not much to be gained by dropping the inheritance however it is possible, but you'd need to refactor it slightly depending on which methods were required by the interface:

```php

namespace MVC\Model\Form;
class SaveFile \MVC\Model\Form {
	private $save;
	private $uploader;


    public function __construct(\MVC\Model\Form $save, \Upload\File $uploader = null) {
        $this->save = $save;
        $this->uploader = $uploader;
    }

    protected function setNewFileName() {
        $newFileName = time() . '-' . $this->uploader->getName();
        $this->uploader->setName($newFileName);
    }

    public function submit($data) {
        $this->submitted = true;
        $this->setNewFileName();
        // Upload File
        try {
            $this->uploader->upload();
        } catch (\Exception $e) {
            $errors = $this->uploader->getErrors();
            return false;
        }
        $data['file_name'] = $this->uploader->getNameWithExtension();
        return $this->save->submit($data);
    }

}

```

Now `SaveFile` isn't coupled to `Maphper` or `AllOf` which makes it more flexible: It can be used with any form, regarless of whether it uses maphper or respect\validation.

**Comment by MrBenGriffin** [comment] 2016-07-15 15:24
Oh - @TomBZombie, that's beginning to look like an excellent solution.

Here is what I was doing just now - sort of works also!, but it's a bit contrived!! 
````php
<?php
class Bar {
	public function do() { return Bar::class; }
}
class Bim {
	public function say() { return Bim::class; }
}

class Foo {
   private $bar;
   public function __construct( $closure ) {
   		$this->bar = $closure(Bar::class);
   }
   public function remark() {
   	print($this->bar->do());
   }
}

class SpecialFoo extends Foo {
   private $bim;
   public function __construct($closure) {
   		parent::__construct($closure);
   		$this->bim = $closure(Bim::class);
   }
   public function remark() {
		print($this->bim->say());
   }
}

$bar = new Bar(); $bim = new Bim();
$foo_deps = [Bar::class=>$bar,Bim::class=>$bim];
$foo_closure = function($class) use($deps) {return $deps[$class];};

$foo = new Foo($foo_closure);
$bar = new SpecialFoo($foo_closure);
$foo->remark();
$bar->remark();

````

**Comment by MrBenGriffin** [comment] 2016-07-15 15:30
> This would work as long as all of Bar's other constructor arguments were type hinted and weren't the same type (Or subtype) as any of AbstractFoo's dependencies.
Yeah, we wouldn't be doing that sort of thing, and all our arguments are now type hinted.  I'm just wondering if we may not do something more like the named array instead, and then do something like

dice->addRule('abstractfoo', ['constructParams' => [FooDep1::class => new FooDep1,FooDep2::class =>  new FooDep2]);

then we can just use a ...deps container and pick out what we need from it and pass it up..

**Comment by solleer** [comment] 2016-07-15 15:33
@TomBZombie 
The interface is
```php
namespace MVC\Model;
interface Form {
    public function main($data);
    public function submit($data);
    public function success();
}
```

**Comment by TomBZombie** [comment] 2016-07-15 15:40
@solleer  In this case the benefit of refactoring out the inheritance here is negligible. You'd either need to create  `FormData` interface to handle the data, or add wrapper (or __call) methods to the class.

**Comment by TomBZombie** [comment] 2016-07-15 15:42
@MrBenGriffin 

> dice->addRule('abstractfoo', ['constructParams' => [FooDep1::class => new FooDep1,FooDep2::class => new FooDep2]);

Unfortunately this won't work because Dice will only ever see the child class' constructor. The parent class constructor is being called explicitly so dice cannot match up the arguments by type, unless you added each argument to each of the child classes, which is what you were trying to avoid doing in the first place.

**Comment by MrBenGriffin** [comment] 2016-07-15 15:52
Ah - hang on, let me rewrite that.. 
I think it will work for us...

````php
dice->addRule('Foo', ['constructParams' => [Bim::class => new Bim]);
dice->addRule('SpecialFoo', ['constructParams' => [Bim::class => new Bim,Baz::class => new Baz]);
````

````php
class Foo {
    public function __construct(...$deps) {
        private $bim;
        parent::__construct(...$deps);
        $this->bim  = $deps[bim::class];
    }
}

class SpecialFoo extends Foo {
    private $baz;
    public function __construct(...$deps) {
        parent::__construct(...$deps);
        $this->baz  = $deps[Baz::class];
    }
}

//normally we do..
$foo = $dice->create('Foo');

//occasionally we do..
$foo = $dice->create('SpecialFoo');
````

I'm wondering if the _constructParams_ will have dice rules applied to it as if it were in the __construct ?

**Comment by TomBZombie** [comment] 2016-07-15 16:02
constructParams will not, you can do this:

```php
dice->addRule('SpecialFoo', ['constructParams' =>[ ['instance' => function() use ($dice) { 
return $dice->create('Bim'); } ] ] );

```

Another option you have is this:

```php
class Foo extends AbstractClass {
   private $bar;
   public function __construct(\Closure $parentConstruct, $ar ) {
         $parentConstruct($this);
         $this->bar = $bar;
   }
   public function remark() {
    print($this->bar->do());
   }
}



$dice->addRule('AbstractClass', ['substitutions' => ['Closure' => function($obj) use($dice) {

$callParent = function() use ($dice) {
    parent::__construct($dice->create('BaseClassDep1), $dice->create('BaseClassDep2);
};

$callParent = $callParent->bindTo($obj, $obj);
$callParent();
});
```

**Comment by MrBenGriffin** [comment] 2016-07-15 16:05
oh.. Haha. I must have missed out something in your earlier example.
I -do- have to go now..  I will think more about this next week.
I really appreciate the time you have given to this, btw.  TNX

**Comment by MrBenGriffin** [comment] 2016-07-20 16:48
Hi there again!
I tried to get your ( @TomBZombie ) examples to work above, but I had not much joy with that (I just got lots of errors).

However, I managed to get Dice working with an _extension_ to one of my ideas above - I enclose a full working file.

A 'weakness' is that each class involved must now have a rule set for it, because (current version of) dice doesn't know about how to compose a set of dependencies from using ReflectionClass::getConstructor(); 

A 'strength' is that now we can use inheritance without having to know anything about our abstract classes - which is very useful when we are making dependency changes to our abstract classes and when we have many class specialisations.

````php
<?php
mb_internal_encoding('UTF-8');
spl_autoload_register();
require 'vendor/autoload.php';

//Random 'dependency' classes
class Bar {
    public function do() { return Bar::class; }
};
class Bim {
    public function say() { return Bim::class; }
};
class Foo {
   private $bar;
   public function __construct($_deps) {
        $this->bar = $_deps[Bar::class];
   }
   public function run() {
    print($this->bar->do());
   }
};

//SpecialFoo knows nothing about Foo
class SpecialFoo extends Foo {
    private $bim;
    public function __construct($_deps) {
        parent::__construct($_deps);
        $this->bim  = $_deps[Bim::class];
    }
   public function run() {
        print($this->bim->say());
        print(parent::run());
   }    
};

//RULES
$dice = new \Dice\Dice;
//note that in the below, the constructor is an array of class instances.
$dice->addRule(Foo::class, 
	['constructParams' => [[Bar::class=>['instance' => Bar::class]]]]
);

//INHERIT SpecialFoo array from  Foo, 
// so that SpecialFoo doesn't need to know about Foo's dependencies even in the rules...
// (Otherwise we are just moving the problem into the rules)
$fooCp = $dice->getRule(Foo::class)['constructParams'][0];
$fooCp[Bim::class] = array('instance' => Bim::class); //Add SpecialFoo Dependencies.
$dice->addRule(SpecialFoo::class,['constructParams' => [ $fooCp ]]);

//Run Application using Dice.
echo("Dice:");
$app1 = $dice->create('SpecialFoo'); $app1->run();
echo(";");
$app2 = $dice->create('Foo'); $app2->run();
echo(" NoDice:");
//Run application without using Dice.
$_deps = [Bim::class=>new Bim(),Bar::class=>new Bar()];
$sf = new SpecialFoo($_deps); $sf->run();
echo(";");
$f = new Foo($_deps); $f->run();
````
Using the dependency array **_deps**, if we want to add dependencies to Foo we don't need to know anything at all about SpecialFoo, neither in SpecialFoo's __construct() nor in it's Dice rules.

Of course, it would be **very nice** (yes, its a hint) if Dice could handle a **_deps** array for us without us having to explicitly declare the rules. I believe that you could do it elegantly in a few lines, @TomBZombie  :-D

**Comment by MrBenGriffin** [comment] 2016-07-20 17:22
Looking at the latest code I just wrote, I'm wondering if using an ArrayObject (for _deps)  may be better than using an array, in that we may be able to use existing substitutions for each constructor, and resolve a lot more that way without having to modify dice. 
Of course, having a nice way to inherit (and extend) the way in which an ArrayObject is constructed for a base class is what we would still need.

**Comment by TomBZombie** [comment] 2017-02-22 16:07
apologies for the very late reply! the problem with this approach, of course, is that it's a brittle API.

Try this:

```
$_deps = [];
$sf = new SpecialFoo($_deps); $sf->run();
```

One of the most powerful features about OOP is that you can enforce types. By specifying 

```php
class Bar {
public function __construct(Foo $foo) {
    $this->foo = $foo;
}

public function run() {
    $this->foo->baz();
}
}
```

It's not possible to construct the object without supplying it with a valid `Foo` instance. This gives a firm contract and enforces some rigidity.

There's no way that `$f = new Bar(new Foo); $f->run();` will error because `$this->foo` must be valid `Foo` instance. With your code above that contract is not enforced. See https://r.je/constructor-injection-vs-setter-injection.html for a similar problem.

**Closed** 2018-01-12 16:07 UTC
