### ISSUE TITLE
Respect\Validation

### ISSUE THREAD

**Issue by solleer** [Level-2/Dice#113] opened 2016-06-13 15:56 UTC
Whenever I try to use dice to create an instance of `Respect\Validation\Rules\AllOf` by feeding in construct params, they are never passed to the object

**Comment by TomBZombie** [comment] 2016-06-13 15:59
I'll need some more information than this. Please provide the class API and the rule you are using.

**Comment by solleer** [comment] 2016-06-13 16:01
https://github.com/Respect/Validation/blob/master/docs/CONCRETE_API.md

**Comment by solleer** [comment] 2016-06-13 16:02
Its whenever I set the constructParams rule none of the classes are passed to the AllOf rule

**Comment by TomBZombie** [comment] 2016-06-13 16:02
Ah, nevermind I found it. The problem is that the constructor doesn't actually have any arguments:

```php

    public function __construct()
    {
        $this->addRules(func_get_args());
    }

```
As a workaround you're better off  calling `addRules` manually.

**Comment by solleer** [comment] 2016-06-13 16:03
Thought it had something to do with that

**Comment by TomBZombie** [comment] 2016-06-13 16:05
Ideally that constructor should be:

```php
    public function __construct(...$args)
    {
        $this->addRules($args);
    }
```

which would work with Dice.

**Comment by TomBZombie** [comment] 2016-06-13 16:17
I've looked at fixing this in Dice, but I don't think this can be be fixed without reintroducing #85. Ideally variadic functions should note they're variadic in the method header.

**Comment by solleer** [comment] 2016-06-13 17:07
Do you know of any input validators that follow better practice

**Comment by TomBZombie** [comment] 2016-06-13 17:13
`Respect\Validation` should work if you  use Dice's `call` feature to call `addRules` instead of `constructParams`. Alternatively add a PR for the change I mentioned above. Since the library targets 5.6+ I don't think they'll have an issue merging it, `...` is preferred over `func_get_args()` anyway: 

> Variable-length argument lists ¶
> 
> PHP has support for variable-length argument lists in user-defined functions. This is implemented using the ... token in PHP 5.6 and later, and using the func_num_args(), func_get_arg(), and func_get_args() functions in PHP 5.5 and earlier.

http://php.net/manual/en/functions.arguments.php#functions.variable-arg-list.new

**Comment by solleer** [comment] 2016-06-13 17:14
I now get formed objects but I have trouble getting the input errors

**Comment by TomBZombie** [comment] 2016-06-13 17:28
I'm not familiar with the library so I can't really help but whatever you were sending to the constructor as individual arguments needs to be wrapped in an array for passing to `addRules`.

**Comment by solleer** [comment] 2016-06-13 17:29
I've got everything working now. I just don't like their syntax and using DI is messy

**Closed** 2016-07-20 23:46 UTC
